### ISSUE TITLE
Expanding this repo

### ISSUE THREAD

**Issue by genotrance** [niv/nim-docset#1]
Hello @niv,
Glad that you have created and are maintaining this repo. I had some proposals I wanted to run by you and see your interest.

I have created a docset script that uses your repo and generates docsets quickly. I have been posting them to the [forum](https://forum.nim-lang.org/t/5050) as you may have already noticed as well as on the Kapeli [repo](https://github.com/Kapeli/Dash-User-Contributions/tree/master/docsets/Nim).

I would like store this script here to make this more seamless when new releases are posted. Please let me know if you are okay with accepting PRs here or if I should do this elsewhere.

TODO
- Add docset.nims to enable automation of doc generation
  - Generate versioned docs - `"package" = "nim-x.x.x" for forum posting
  - Generate unversioned docs to push onto Kapeli repo
- Add details in README on how to use script and how to create PRs for Kapeli repo
- Post releases into this repo's releases page instead of bintray
- Add notes in Nim [wiki](https://github.com/nim-lang/Nim/wiki/Creating-a-release) to do this for every release

Ideally, this is all done in the nim-lang domain but we can start here for now.

Let me know your thoughts and thanks in advance.

cc @Araq @dom96 @narimiran @krux02 for their thoughts as well.

**Comment by niv** [comment]
Hey,

thanks for your effort here. I've just tried the one downloaded via Dash and it seems to work well!

I'm obviously happy to accept PRs. I don't have much time to manage this thing, so if you would like to have contrib access or move it to the nim-lang namespace I'm happy to discuss that too.

Let me know what you need!

**Comment by genotrance** [comment]
I'll just fork this and maintain instead. The fork link will maintain credit to you and wicast.

Thanks again for your work!
